language: go

go:
  - 1.9.x
  # - tip
before_install:
  - go env
  - make deps
  # - go get github.com/mattn/goveralls
  # - go get github.com/modocache/gover
script:
  - go test ./...
  # - $GOPATH/bin/gover
  # - $GOPATH/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
cache:
  directories:
    - $GOPATH/bin
  timeout: 1000
