language: go
go:
  - 1.10.x
  - tip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make coverage
after_success:
  - ./cc-test-reporter after-build --exit-code $EXIT_CODE
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $GOPATH/bin
    - vendor
  timeout: 1000
notifications:
  email:
    on_success: never
    on_failure: always
